name: Checkout Repo
on: [push]

jobs:
    Check-Out-and-Display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files before
              run: |
                pwd
                ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List file after
              run: |
                pwd
                ls -a
                
