name: Checkout Repo
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List files before
              run: |
                pwd
                ls -a
            - uses: actions/checkout@v3
            - name: List files before
              run: |
                pwd
                ls -a

    Check-Out-and-Display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files before
              run: |
                pwd
                ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List file after
              run: |
                pwd
                ls -a
                
