name: Enviroment Variable
on: [push]

env:
    WF_LEVEL_VAR: Availbale in all job in this WF

jobs:
    env-var-and-context:
        runs-on: ubuntu-latest
        env:
            JOB_LEVEL_VAR: Availbale in all steps in env-var-and-context job
        # if: $GITHUB_REF == 'refs/heads/main' # DO NOT USE THIS
        if: github.ref == 'refs/heads/main'
        steps:
            - name: LOG ENV VAR # Evaluated in Runner machine
              run: echo $GITHUB_REF
            - name: LOG Context # Evaluated before sending command Runner machine
              run: echo ${{ github.ref}}
            - name: Set Env Var
              run: |
                echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"
                echo "STEP_LEVEL_VAR=$RANDOM" >> "$GITHUB_ENV"
            - name: Multiline Env VAR
              run: |
                DELIMETER=1234
                echo "RANDOM_JOKE_VAR<<$DELIMETER" >> "$GITHUB_ENV"
                echo "Here is a Joke: " >> "$GITHUB_ENV"
                curl -s https://icanhazdadjoke.com/  >> "$GITHUB_ENV"
                echo ""  >> "$GITHUB_ENV"
                echo $DELIMETER >> "$GITHUB_ENV"
            - name: Log Custom ENV Var
              env:
                STEP_LEVEL_VAR: Availbale ONLY in this step
                WF_LEVEL_VAR: Overwritten Env Var
              run: |
                echo '${{ github.JOB_LEVEL_VAR }}'
                echo $JOB_LEVEL_VAR
                echo $WF_LEVEL_VAR
                echo $STEP_LEVEL_VAR
                echo $NEW_ENV_VAR
                echo $RANDOM_JOKE_VAR



