name: Matrix
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-versions: [12, 14 15]
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
      - run: node -v

