name: Matrix
on: [push]

jobs:
  node-matrix:
    # continue-on-error: true
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          node-versions: [13, 14, 15]
        # max-parallel: 2
        # fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
      - run: node -v

