name: Workflow Run
on:
    workflow_run:
        workflows: [Repository Events]
        types: [completed]
jobs:
    echo-string:
        runs-on: ububtu-latest
        steps:
            - run: echo "Triggered because 'Repository Event" has been completed

